/**
 * generate-tokens.ts — Auto-generates src/data/tokens.generated.ts from @giro-ds/tokens build output
 * Run: pnpm --filter @giro-ds/mcp generate:tokens
 *
 * Reads packages/tokens/build/css/tokens.css (gerado pelo Style Dictionary) e extrai
 * todos os CSS custom properties, inferindo a categoria a partir do prefixo do token.
 */
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const CSS_INPUT = path.resolve(__dirname, '../../tokens/build/css/tokens.css');
const OUTPUT_FILE = path.resolve(__dirname, '../src/data/tokens.generated.ts');

interface TokenEntry {
  name: string;
  value: string;
  category: string;
}

function inferCategory(tokenName: string): string {
  if (tokenName.startsWith('--border-radius')) return 'border-radius';
  if (tokenName.startsWith('--border-width')) return 'border-width';
  if (tokenName.startsWith('--color-brand')) return 'color-brand';
  if (tokenName.startsWith('--color-feedback')) return 'color-feedback';
  if (tokenName.startsWith('--color-neutral')) return 'color-neutral';
  if (tokenName.startsWith('--color')) return 'color';
  if (tokenName.startsWith('--spacing')) return 'spacing';
  if (tokenName.startsWith('--font-')) return 'typography';
  return 'other';
}

function parseCssTokens(css: string): TokenEntry[] {
  const tokens: TokenEntry[] = [];
  // Matches lines like:   --token-name: value;
  const regex = /^\s*(--[\w-]+)\s*:\s*(.+?)\s*;/gm;
  let match: RegExpExecArray | null;

  while ((match = regex.exec(css)) !== null) {
    const name = match[1];
    const value = match[2];
    tokens.push({ name, value, category: inferCategory(name) });
  }

  return tokens;
}

function generateFileContent(tokens: TokenEntry[]): string {
  const lines = tokens.map(
    (t) => `  { name: '${t.name}', value: '${t.value.replace(/'/g, "\\'")}', category: '${t.category}' },`,
  );

  return `/**
 * DO NOT EDIT DIRECTLY — this file was auto-generated by scripts/generate-tokens.ts
 * Run \`pnpm --filter @giro-ds/mcp generate:tokens\` to regenerate.
 */
import type { DesignToken } from '../types.js';

export const GENERATED_TOKENS: DesignToken[] = [
${lines.join('\n')}
];
`;
}

function main() {
  if (!fs.existsSync(CSS_INPUT)) {
    console.error(`[generate-tokens] CSS file not found: ${CSS_INPUT}`);
    console.error('[generate-tokens] Run "pnpm --filter @giro-ds/tokens build" first.');
    process.exit(1);
  }

  const css = fs.readFileSync(CSS_INPUT, 'utf-8');
  const tokens = parseCssTokens(css);

  if (tokens.length === 0) {
    console.warn('[generate-tokens] No tokens found in CSS file. Check the file format.');
    process.exit(1);
  }

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, generateFileContent(tokens), 'utf-8');

  console.log(`[generate-tokens] Generated ${tokens.length} tokens -> ${OUTPUT_FILE}`);
}

main();
